-- HR 계정 SQL 50문제
-- 1. 연봉이 12000 이상되는 직원들의 LAST_NAME 및 연봉을 조회한다.
SELECT 
	LAST_NAME , SALARY 
FROM 
	EMPLOYEES e
WHERE 
	SALARY >= 12000;
	
-- 2. 사원번호가 176 인 사람의 LAST_NAME 과 부서 번호를 조회한다.
SELECT 
	LAST_NAME , DEPARTMENT_ID 
FROM 
	EMPLOYEES e
WHERE 
	EMPLOYEE_ID = 176;

-- 3. 연봉이 5000 에서 12000의 범위 이외인 사람들의 LAST_NAME 및 연봉을 조회힌다.
SELECT 
	LAST_NAME , SALARY 
FROM 
	EMPLOYEES e
WHERE 
	SALARY >= 5000 AND SALARY <=12000;

SELECT 
	LAST_NAME , SALARY 
FROM 
	EMPLOYEES e
WHERE 
	SALARY BETWEEN 5000 AND 12000;

-- 4. 2002/02/20 일부터 2005/05/01 사이에 고용된 사원들의 LAST_NAME 사번, 고용일자를 조회한다.
--    고용일자 순으로 정렬한다.

SELECT * FROM EMPLOYEES;

SELECT 
	LAST_NAME , EMPLOYEE_ID , HIRE_DATE 
FROM 
	EMPLOYEES e
WHERE 
	HIRE_DATE BETWEEN '2002/02/20' AND '2005/05/01'
ORDER BY 
	HIRE_DATE;

SELECT 
	LAST_NAME , EMPLOYEE_ID , HIRE_DATE 
FROM 
	EMPLOYEES e
WHERE 
	HIRE_DATE >= '2002/02/20' AND HIRE_DATE <= '2005/05/01'
ORDER BY 
	HIRE_DATE;

SELECT 
	LAST_NAME , EMPLOYEE_ID , HIRE_DATE 
FROM 
	EMPLOYEES e
WHERE 
	HIRE_DATE >= TO_DATE('2002/02/20') AND HIRE_DATE <= TO_DATE('2005/05/01')
ORDER BY 
	HIRE_DATE;

-- 5. 20 번 및 50 번 부서에서 근무하는 모든 사원들의 LAST_NAME 및 부서 번호를 알파벳순으로 조회한다.
SELECT 
	LAST_NAME , DEPARTMENT_ID 
FROM 
	EMPLOYEES e 
WHERE 
	DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50
ORDER BY 
	LAST_NAME;

SELECT 
	LAST_NAME , DEPARTMENT_ID 
FROM 
	EMPLOYEES e 
WHERE 
	DEPARTMENT_ID IN (20,50) 
ORDER BY 
	LAST_NAME;


-- 6. 20 번 및 50 번 부서에 근무하며, 연봉이 5000 ~ 12,000 사이인 사원들의 LAST_NAME 및 연봉을 조회한다.

SELECT 
	LAST_NAME , SALARY 
FROM 
	EMPLOYEES e 
WHERE 
	DEPARTMENT_ID IN (20,50) AND SALARY BETWEEN 5000 AND 12000;


SELECT 
	LAST_NAME , SALARY 
FROM 
	EMPLOYEES e 
WHERE 
	(DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50) AND (SALARY >= 5000 AND SALARY <= 12000);


-- 7. 2002년도에 고용된 모든 사람들의 LAST_NAME 및 고용일을 조회한다.
SELECT LAST_NAME , HIRE_DATE FROM	EMPLOYEES e WHERE HIRE_DATE LIKE '2002%'; -- 안나옴 왜? 문자로 비교하면 년도가 2자리로 바뀜

SELECT LAST_NAME , HIRE_DATE FROM	EMPLOYEES e WHERE HIRE_DATE LIKE '02%';

SELECT LAST_NAME , HIRE_DATE FROM	EMPLOYEES e WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2002;

SELECT LAST_NAME , HIRE_DATE FROM	EMPLOYEES e WHERE HIRE_DATE >= '02/01/01' AND HIRE_DATE <= '02/12/31' ;


SELECT LAST_NAME , HIRE_DATE||' ' FROM	EMPLOYEES e; -- 날짜를 문자로 연산하면 yy/mm/dd형태로 나온다.

-- 7-1. 이번달에 입사원 사원의 LAST_NAME 및 고용일을 조회한다.
SELECT LAST_NAME , HIRE_DATE FROM	EMPLOYEES e WHERE EXTRACT(MONTH FROM HIRE_DATE) = EXTRACT(MONTH FROM SYSDATE);

SELECT 
	LAST_NAME , HIRE_DATE, SUBSTR(SYSDATE, 3, 4) 
FROM	
	EMPLOYEES 
WHERE 
	HIRE_DATE LIKE '%'||SUBSTR(SYSDATE, 3, 4)||'%';

-- 아래와 같이하면 01일이나 2001년에 입사한 사원도 나온다.
SELECT 
	LAST_NAME , HIRE_DATE, SUBSTR(SYSDATE, 4, 2) 
FROM	
	EMPLOYEES 
WHERE 
	HIRE_DATE LIKE '%'||SUBSTR(SYSDATE, 4, 2)||'%';

-- 8-1. 매니저가 없는 사람들의 LAST_NAME 및 JOB_ID 를 조회한다.
SELECT 
	LAST_NAME , JOB_ID 
FROM 
	EMPLOYEES e 
WHERE 
	MANAGER_ID IS NULL;

-- 8-2. 매니저가 있는 사람들의 LAST_NAME 및 JOB_ID 를 조회한다.
SELECT 
	LAST_NAME , JOB_ID 
FROM 
	EMPLOYEES e 
WHERE 
	MANAGER_ID IS NOT NULL;


-- 9. 커미션을 버는 모든 사원들의 LAST_ANME, 연봉 및 커미션을 조회한다.
--    연봉 역순, 커미션 역순차로 정렬한다.

SELECT 
	LAST_NAME , SALARY , COMMISSION_PCT 
FROM 
	EMPLOYEES e 
WHERE 
	COMMISSION_PCT IS NOT NULL
ORDER by 
	SALARY DESC, COMMISSION_PCT desc;

-- 10. LAST_NAME 의 네번째 글자가 a 인 사원들의 LAST_NAME 을 조회한다.
SELECT 
	LAST_NAME 
FROM 
	EMPLOYEES e 
WHERE 
	LAST_NAME LIKE '___a%';


